# Basic Python

## 1. Split this string

In [40]:
s = "Hi there Sam!"

In [39]:
s = "Hi there Sam!"
print(s.split(sep=" "))

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [44]:
planet = "Earth"
diameter = 12742
print("The diameter of Earth is {} kilometers".format(diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [51]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [58]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
np.ones(10)*5    

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [57]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
import numpy as np
d=np.arange(9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
##  a= np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [27]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [28]:
import pandas as pd
import numpy as np

In [29]:
d1=pd.DataFrame([[1,2],[3,4],[5,6]])
d1

0  1
0  1  2
1  3  4
2  5  6

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [3]:
import pandas as pd
  
per1 = pd.date_range(start ='1-1-2023', 
         end ='1-02-2023',freq ='5H')
  
for val in per1:
    print(val)

2023-01-01 00:00:00
2023-01-01 05:00:00
2023-01-01 10:00:00
2023-01-01 15:00:00
2023-01-01 20:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [23]:
pd.DataFrame([[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]])

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24